version: 0.2

env:
  parameter-store:
    DOCKER_USER: /demo/docker-credencials/username
    DOCKER_PASS: /demo/docker-credencials/password

  variables:
    DOCKER_URL: docker.io  
    
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin $DOCKER_URL
      - echo "Logged in to Docker Hub"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_URL/$DOCKER_USER/demo:latest" .
      - docker push "$DOCKER_URL/$DOCKER_USER/demo:latest"
      - docker logout 
      - echo "logout"
      
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: "."
